app/views/answer_views.py
from flask import Blueprint, render_template, request, url_for
from app.forms import AnswerForm
from app import db
from app.models import Answer, Question
from datetime import datetime
from werkzeug.utils import redirect

answer = Blueprint('answer', __name__, url_prefix='/answer')

# 작성과 수정을 하나의 폼에서 사용할 예정입니다.
@answer.route('/create/<int:question_id>/', methods=['POST'])
def create(question_id):
    form = AnswerForm()
    # question 화면 가져오기
    question = Question.query.get_or_404(question_id)
    # question = Question.query.all(question_id)
    if form.validate_on_submit():
        # 어느 글에서 오는지 (question_id)
        # content = request.form['content']
        a = Answer(content=form.content.data, create_date=datetime.now())

        # answer의 question_id 필드에 추가
        # answer_set은 model에 정의한 답변에서 글을 끌어오기위한 backref의 객체명입니다.
        question.answer_set.append(a)
        db.session.add(a)
        db.session.commit()
        # question으로 불리우는 basic_views.py의 detail 함수를 호출하는데 question_id를 함께 전달
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

app/views/question_views.py
from flask import Blueprint, render_template, request, redirect, g, flash, url_for
from app.models import Question, Answer
from datetime import datetime
from app import db
from app.forms import QuestionForm, AnswerForm
from app.views.auth_views import login_required

# 우리가 부를 이름, flask 프레임워크가 찾을 이름, 라우팅주소
question = Blueprint('question', __name__, url_prefix='/question')

@question.route('/detail/<int:question_id>/')
def detail(question_id):
    # AnswerForm을 추가합니다
    form = AnswerForm()
    # question = Question.query.get(question_id)
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

# pagenation으로 글 목록 출력하기
@question.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)  # 페이지
     # 시간순으로 최신글을 맨 위로 올릴 것인지
    question_list = Question.query.order_by(Question.create_date.desc())
    # 10개씩 끊어서 출력 
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)


@question.route('/create/', methods=('GET', 'POST'))
@login_required # 접근 권한을 확인하기 위한 데코러이터 
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('basic.index'))
    return render_template('question/question_form.html', form=form)

@question.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    # 원본 글을 미리 가져옵니다 
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@question.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

app/templates/question/question_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">

    <!-- flash 오류 -->
    <!-- 물론 수정은 로그인 한 사용자와 글 작성자가 동일한 경우에만 가능하기 때문에 이 오류가 표시될 일은 없을 것이다. 하지만 비 정상적인 방법으로 질문을 수정할 경우 오류를 보여주어야 하므로 필요한 부분이다. -->
    <!-- {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %} -->

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
      
         
            <!-- 글쓴이 추가. 답변 목록에도 추가 -->
            <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{ question.user.username }}</div>
                <div>{{ question.create_date|date_time }}</div>
            </div>
        </div>

        <!-- 수정 버튼 추가 -->
        <div class="my-3">
            {# 로그인한 사용자와 글쓴이가 같은 경우에만 보여야 하므로 {% if g.user == question.user %}를 사용했다. #}
            {% if g.user == question.user %}
            <a href="{{ url_for('question.modify', question_id=question.id) }}"
                class="btn btn-sm btn-outline-secondary">수정</a>

            <!-- 삭제버튼에 자바스크립트 심기 -->
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
            data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
            {% endif %}
               
               <!-- 수정버튼 변경 완료 - 이후 question_views.py 수정 -->
            </div>
        </div>
    </div>

    <!-- 답변 목록 -->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            


                <!-- 글쓴이 추가 -->
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date|date_time }}</div>
            </div>

            <!-- 수정 버튼 추가 -->
            <div class="my-3">
                {% if g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        <!-- 질문 상세 템플릿에 폼이 추가되었으므로 question_views.py 파일의 detail 함수도 폼을 사용하도록 수정해야 한다. 이 과정이 없으면 템플릿에서 form 객체를 읽지 못해 오류가 난다. -->
        {{ form.csrf_token }}
        
        {% include "form_errors.html" %}
      
        <div class="mb-3">
            <!-- <textarea name="content" id="content" class="form-control" rows="10"></textarea> -->

            <!-- 로그아웃 상태에서 답변 등록 불가능하게 만들기 -->
            <textarea {% if not g.user %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary"> 
    </form>
</div>
{% endblock %}
<!-- 자바스크립트 추가. 이후 question_views.py에 view 추가 -->
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

app/templates/question/question_form.html
# app/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 올리기</h5>
    <!-- <form class="my-3" action="{{ url_for('question.create') }}"> -->
    <form method="post" class="my-3" action="{{ url_for('question.create') }}">

       {{ form.csrf_token }}
		<!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->

        {# Form에서 작성한 라벨 #}
        {{ form.subject.label }}

		{# Form에서 작성한 필드. 값을 입력 받아야 하는 '폼'이므로 호출연산자로 작성 #}
        {{ form.subject(class="form-control") }}
        <p>
        {{ form.content.label }}
        {{ form.content(class="form-control") }}
        <p>   
        <button type="submit" class="btn btn-dark">저장</button>
    </form>
</div>
{% endblock %}

app/templates/question/question_list.html
{% extends 'base.html' %}

{% block content %}
    <!-- 질문 목록 -->
{#  render_template 함수에서 전달받은 질문 목록 데이터 question_list가 있는지 검사 #}

<div class="container my-3">
    {% if g.user %}
    <a href="{{ url_for ('question.create') }}" class="btn btn-dark">질문 등록</a>
    {% endif %}
    <p>

    <table class="table">
        <thead>
        <tr class="table-danger">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <!-- <td>{{ loop.index }}</td> -->
            <!-- <td>{{ question.id }}</td> -->
            <!-- <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td> -->
            
            <td>{{ ((question_list.page-1) * question_list.per_page) + loop.index }}</td>
            <td>
                <a href="{{ url_for('question.detail', question_id=question.id) }}" style="text-decoration: none; color:darkslateblue">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date | date_time}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
                <!-- 이전 페이지가 있는 경우에는 "이전" 링크가 활성화, 이전 페이지가 없는 경우에는 "이전" 링크가 비활성화 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지번호 -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
                <!-- 현재 페이지와 같을 경우에는 active클래스를 적용하여 강조 -->
        <li class="page-item active" aria-current="page">
            <a class="page-link bg-danger border-danger focus-ring focus-ring-warning" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    </div>
    {% endblock %}